{include("AsByDomain/GeneralDomain/as4ABC.asl")}
{include("AsByDomain/GeneralDomain/as4C2C.asl")}
{include("AsByDomain/GeneralDomain/as4Class.asl")}
{include("AsByDomain/GeneralDomain/as4DStd.asl")}
{include("AsByDomain/GeneralDomain/as4GbyA.asl")}
{include("AsByDomain/GeneralDomain/as4NFAO.asl")}
{include("AsByDomain/GeneralDomain/as4NegCons.asl")}
{include("AsByDomain/GeneralDomain/as4PFAO.asl")}
{include("AsByDomain/GeneralDomain/as4VofVC.asl")}
{include("AsByDomain/GeneralDomain/asMJAdPA.asl")}
{include("AsByDomain/GeneralDomain/pns4PA4A.asl")}
{include("AsByDomain/GeneralDomain/as4BAdH.asl")}
{include("AsByDomain/GeneralDomain/as4C2E.asl")}
{include("AsByDomain/GeneralDomain/as4Commit.asl")}
{include("AsByDomain/GeneralDomain/as4E2C.asl")}
{include("AsByDomain/GeneralDomain/as4IC.asl")}
{include("AsByDomain/GeneralDomain/as4NH.asl")}
{include("AsByDomain/GeneralDomain/as4P2K.asl")}
{include("AsByDomain/GeneralDomain/as4T.asl")}
{include("AsByDomain/GeneralDomain/as4sign.asl")}
{include("AsByDomain/GeneralDomain/asNecCond.asl")}
{include("AsByDomain/GeneralDomain/rs4A4P.asl")}
{include("AsByDomain/HospitalBedAllocation/AboutAgeGroup/asBBRAG.asl")}
{include("AsByDomain/HospitalBedAllocation/AboutAgeGroup/asBRBAG.asl")}
{include("AsByDomain/HospitalBedAllocation/AboutAgeGroup/asPAGAdult.asl")}
{include("AsByDomain/HospitalBedAllocation/AboutAgeGroup/asPAGChild.asl")}
{include("AsByDomain/HospitalBedAllocation/AboutAgeGroup/asPAGTeenager.asl")}
{include("AsByDomain/HospitalBedAllocation/AboutAgeGroup/asPBAG.asl")}
{include("AsByDomain/HospitalBedAllocation/AboutAttendance/asBRAt.asl")}
{include("AsByDomain/HospitalBedAllocation/AboutAttendance/asBRBAt.asl")}
{include("AsByDomain/HospitalBedAllocation/AboutAttendance/asPBAt.asl")}
{include("AsByDomain/HospitalBedAllocation/AboutBedSuitability/asAGUnsuitable.asl")}
{include("AsByDomain/HospitalBedAllocation/AboutBedSuitability/asCareUnsuitable.asl")}
{include("AsByDomain/HospitalBedAllocation/AboutBedSuitability/asGenderUnsuitable.asl")}
{include("AsByDomain/HospitalBedAllocation/AboutBedSuitability/asSpecialityUnsuitable.asl")}
{include("AsByDomain/HospitalBedAllocation/AboutBedSuitability/asSuitable.asl")}
{include("AsByDomain/HospitalBedAllocation/AboutCare/asBBRCare.asl")}
{include("AsByDomain/HospitalBedAllocation/AboutCare/asBRBCare.asl")}
{include("AsByDomain/HospitalBedAllocation/AboutCare/asPBCare.asl")}
{include("AsByDomain/HospitalBedAllocation/AboutGender/asBBRGender.asl")}
{include("AsByDomain/HospitalBedAllocation/AboutGender/asBRBGender.asl")}
{include("AsByDomain/HospitalBedAllocation/AboutGender/asPBGender.asl")}
{include("AsByDomain/HospitalBedAllocation/AboutGender/asPGenderFemale.asl")}
{include("AsByDomain/HospitalBedAllocation/AboutGender/asPGenderMale.asl")}
{include("AsByDomain/HospitalBedAllocation/AboutIsolation/asBBRIso.asl")}
{include("AsByDomain/HospitalBedAllocation/AboutIsolation/asBRBIso.asl")}
{include("AsByDomain/HospitalBedAllocation/AboutIsolation/asPBIso.asl")}
{include("AsByDomain/HospitalBedAllocation/AboutPuerperal/asBBRPuerperal.asl")}
{include("AsByDomain/HospitalBedAllocation/AboutPuerperal/asBRBPuerperal.asl")}
{include("AsByDomain/HospitalBedAllocation/AboutPuerperal/asPBPuerperal.asl")}
{include("AsByDomain/HospitalBedAllocation/AboutRouting/asBBRouting.asl")}
{include("AsByDomain/HospitalBedAllocation/AboutRouting/asBRBRouting.asl")}
{include("AsByDomain/HospitalBedAllocation/AboutRouting/asPBRouting.asl")}
{include("AsByDomain/HospitalBedAllocation/AboutRouting/asPRouting.asl")}
{include("AsByDomain/HospitalBedAllocation/AboutSpeciality/asBBRSpeciality.asl")}
{include("AsByDomain/HospitalBedAllocation/AboutSpeciality/asBRBSpeciality.asl")}
{include("AsByDomain/HospitalBedAllocation/AboutSpeciality/asPBSpeciality.asl")}
{include("AsByDomain/HospitalBedAllocation/AboutStay/asBBRStay.asl")}
{include("AsByDomain/HospitalBedAllocation/AboutStay/asBRBStay.asl")}
{include("AsByDomain/HospitalBedAllocation/AboutStay/asPBStay.asl")}
{include("AsByDomain/HospitalBedAllocation/Others/asBVacates.asl")}
{include("AsByDomain/HospitalBedAllocation/Others/asPNeedAssistance.asl")}
{include("AsByDomain/LegalDomain/as4AnV1.asl")}
{include("AsByDomain/LegalDomain/as4AnV2.asl")}
{include("AsByDomain/LegalDomain/as4EC.asl")}
{include("AsByDomain/LegalDomain/as4ER.asl")}
{include("AsByDomain/LegalDomain/as4VC.asl")}
{include("AsByDomain/LegalDomain/as4WT.asl")}
{include("AsByDomain/LegalDomain/asCExp.asl")}
{include("AsByDomain/LegalDomain/asFactCmpV1.asl")}
{include("AsByDomain/LegalDomain/asFactCmpV2.asl")}
{include("AsByDomain/LegalDomain/asP2KAdP.asl")}
{include("AsByDomain/LegalDomain/asP4P.asl")}