{include("HospitalBedAllocation/AboutAgeGroup/asBBRAG.asl")}
{include("HospitalBedAllocation/AboutAgeGroup/asBRBAG.asl")}
{include("HospitalBedAllocation/AboutAgeGroup/asPAGAdult.asl")}
{include("HospitalBedAllocation/AboutAgeGroup/asPAGChild.asl")}
{include("HospitalBedAllocation/AboutAgeGroup/asPAGTeenager.asl")}
{include("HospitalBedAllocation/AboutAgeGroup/asPBAG.asl")}
{include("HospitalBedAllocation/AboutAttendance/asBRAt.asl")}
{include("HospitalBedAllocation/AboutAttendance/asBRBAt.asl")}
{include("HospitalBedAllocation/AboutAttendance/asPBAt.asl")}
{include("HospitalBedAllocation/AboutBedSuitability/asAGUnsuitable.asl")}
{include("HospitalBedAllocation/AboutBedSuitability/asCareUnsuitable.asl")}
{include("HospitalBedAllocation/AboutBedSuitability/asGenderUnsuitable.asl")}
{include("HospitalBedAllocation/AboutBedSuitability/asSpecialityUnsuitable.asl")}
{include("HospitalBedAllocation/AboutBedSuitability/asSuitable.asl")}
{include("HospitalBedAllocation/AboutCare/asBBRCare.asl")}
{include("HospitalBedAllocation/AboutCare/asBRBCare.asl")}
{include("HospitalBedAllocation/AboutCare/asPBCare.asl")}
{include("HospitalBedAllocation/AboutGender/asBBRGender.asl")}
{include("HospitalBedAllocation/AboutGender/asBRBGender.asl")}
{include("HospitalBedAllocation/AboutGender/asPBGender.asl")}
{include("HospitalBedAllocation/AboutGender/asPGenderFemale.asl")}
{include("HospitalBedAllocation/AboutGender/asPGenderMale.asl")}
{include("HospitalBedAllocation/AboutIsolation/asBBRIso.asl")}
{include("HospitalBedAllocation/AboutIsolation/asBRBIso.asl")}
{include("HospitalBedAllocation/AboutIsolation/asPBIso.asl")}
{include("HospitalBedAllocation/AboutPuerperal/asBBRPuerperal.asl")}
{include("HospitalBedAllocation/AboutPuerperal/asBRBPuerperal.asl")}
{include("HospitalBedAllocation/AboutPuerperal/asPBPuerperal.asl")}
{include("HospitalBedAllocation/AboutRouting/asBBRouting.asl")}
{include("HospitalBedAllocation/AboutRouting/asBRBRouting.asl")}
{include("HospitalBedAllocation/AboutRouting/asPBRouting.asl")}
{include("HospitalBedAllocation/AboutRouting/asPRouting.asl")}
{include("HospitalBedAllocation/AboutSpeciality/asBBRSpeciality.asl")}
{include("HospitalBedAllocation/AboutSpeciality/asBRBSpeciality.asl")}
{include("HospitalBedAllocation/AboutSpeciality/asPBSpeciality.asl")}
{include("HospitalBedAllocation/AboutStay/asBBRStay.asl")}
{include("HospitalBedAllocation/AboutStay/asBRBStay.asl")}
{include("HospitalBedAllocation/AboutStay/asPBStay.asl")}
{include("HospitalBedAllocation/Others/asBVacates.asl")}
{include("HospitalBedAllocation/Others/asPNeedAssistance.asl")}